version: '3.1'

services:
  app:
    build: .
    ports:
      - "50051:50051" # Expose the port your app runs on
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password # Replace with your password
      POSTGRES_DB: postgres         # Replace with your database name
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
