version: '3.1'

services:
  app:
    build: .
    ports:
      - "50051:50051" # Expose the port your app runs on
    depends_on:
      - postgres-master
      - redis-master

  postgres-master:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password # Replace with your password
      POSTGRES_DB: postgres       # Replace with your database name
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  postgres-slave:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    depends_on:
      - postgres-master

  redis-master:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  redis-slave:
    image: redis:latest
    restart: always
    ports:
      - "6380:6379"
    depends_on:
      - redis-master

volumes:
  postgres-data:
  redis-data:
