[PostgreSQL.Master]
Host = "my-postgres-container"
Port = 5432
User = "postgres"
Password = "mysecretpassword"
DBName = "mydatabase"

[[PostgreSQL.Slaves]]
Host = "my-postgres-container"
Port = 5432
User = "postgres"
Password = "mysecretpassword"
DBName = "mydatabase"

[Redis.Master]
Addr = "localhost:6379"
Password = ""
DB = 0

[[Redis.Slaves]]
Addr = "localhost:6380"
Password = ""
DB = 0
